name: "New Paper Server"
minecraft:
  loader: "paper"
  version: "1.21.1"

world:
  mode: "generated"
  seed: ""
  name: "world"

plugins: []

configs:
  files:
    - template: "server.properties.hbs"
      output: "server.properties"
      data:
        motd: "New MC Server"
        maxPlayers: 10
        enforceSecureProfile: false
        viewDistance: 10
        onlineMode: true
    - template: "paper-global.yml.hbs"
      output: "config/paper-global.yml"
      data:
        chunkSystem:
          targetTickDistance: 6

overrides:
  - path: "paper-global.yml:chunk-system.target-tick-distance"
    value: 6

mergePolicy:
  arrays: "replace"

